INSERT INTO favorite_food (favorite_food_name) VALUES ('Steak')
INSERT INTO animal (animal_name, scientific_name, favorite_food_id, informational_link)VALUES ('Sumatran orangutan','Pongo abelii','1', 'link')
INSERT INTO animal (animal_name, scientific_name, favorite_food_id, informational_link)VALUES ('Monkey','Pongo abelii','1', 'link')
INSERT INTO animal (animal_name, scientific_name, favorite_food_id, informational_link)VALUES ('Ape','Pongo abelii','1', 'link')
INSERT INTO animal (animal_name, scientific_name, favorite_food_id, informational_link)VALUES ('Rattle Snake','Pongo abelii','1', 'link')
